src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class  User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $full_name;

    /**
     * @ORM\Column(type="date_immutable", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $register_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $sex;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $diet;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $allergies;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_blocked;

    /**
     * @ORM\Column(type="json_array")
     */
    private $roles = [];

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\OrderClient", mappedBy="client")
     */
    private $orderClients;


    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * User constructor.
     * @throws Exception
     */
    public function __construct()
    {
        $this->setRegisterAt(new DateTime());
        $this->full_name = $this->first_name . " " . $this->last_name;
        $this->orderClients = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->full_name;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    /**
     * @param string|null $last_name
     * @return $this
     */
    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    /**
     * @param string|null $first_name
     * @return $this
     */
    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return string|null
     */
    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    /**
     * @param string|null $full_name
     * @return $this
     */
    public function setFullName(?string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return DateTime|null
     */
    public function getBirthday(): ?DateTime
    {
        return $this->birthday;
    }

    /**
     * @param DateTime|null $birthday
     * @return $this
     */
    public function setBirthday(?DateTime $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return DateTime
     */
    public function getRegisterAt(): DateTime
    {
        return $this->register_at;
    }

    /**
     * @param DateTime $register_at
     * @return $this
     */
    public function setRegisterAt(DateTime $register_at): self
    {
        $this->register_at = $register_at;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return string|null
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * @param string $username
     * @return $this
     */
    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return int|null
     */
    public function getSex(): ?int
    {
        return $this->sex;
    }

    /**
     * @param int|null $sex
     * @return $this
     */
    public function setSex(?int $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string|null $email
     * @return $this
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return string|null
     */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /**
     * @param string|null $phone
     * @return $this
     */
    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return string|null
     */
    public function getAddress(): ?string
    {
        return $this->address;
    }

    /**
     * @param string|null $address
     * @return $this
     */
    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return mixed
     */
    public function getDiet()
    {
        return $this->diet;
    }

    /**
     * @param $diet
     * @return $this
     */
    public function setDiet($diet): self
    {
        $this->diet = $diet;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return mixed
     */
    public function getAllergies()
    {
        return $this->allergies;
    }

    /**
     * @param $allergies
     * @return $this
     */
    public function setAllergies($allergies): self
    {
        $this->allergies = $allergies;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @param string $password
     * @return $this
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return bool|null
     */
    public function getIsBlocked(): ?bool
    {
        return $this->is_blocked;
    }

    /**
     * @param bool $is_blocked
     * @return $this
     */
    public function setIsBlocked(bool $is_blocked): self
    {
        $this->is_blocked = $is_blocked;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * @return array
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * @param $roles
     * @return $this
     */
    public function setRoles($roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    //
    //              This methods is needed when UserInterface is used :
    //              "Class must be abstract or implement methods 'eraseCredentials','getSalt'"
    //
    ////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class UserType
 * @package App\Form
 */
class UserType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class)
            ->add('username', TextType::class)
            ->add('password', RepeatedType::class, array(
                'type' => PasswordType::class,
                'first_options' => array('label' => 'Password'),
                'second_options' => array('label' => 'Repeat Password'),
            ))
            ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\OrderClient;
use App\Entity\Product;
use App\Entity\User;
use App\Form\UserType;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Console\Logger\ConsoleLogger;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{

    /**
     * @Route("/mobileLogin", name="user_get", methods={"GET"})
     * @param Request $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     */
    public function mobileLogin(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $username = $request->query->get("username");
        $password = $request->query->get("password");

        $user = $this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['username' => $username]);

        if($user != null and $passwordEncoder->isPasswordValid($user, $password)){
            return $response = new Response(strval($user->getId()));
        }

        return $response = new Response('KO');
    }

    /**
     * @Route("/myOrder", name="user_order", methods={"GET"})
     * @param Request $request
     * @return Response
     */
    public function myOrder(Request $request): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();

        $orders_list = [];
        /**
         * @var OrderClient $orders
         */
        foreach ($user->getOrderClients() as $orders) {
            $removed = array("\"","{","}");
            $tmp_product = $orders->getProducts();

            if (!is_string($tmp_product)){
                $tmp_product = json_encode($tmp_product);
            }

            $products = explode(",", str_replace($removed, "", $tmp_product));

            foreach ($products as $product_detail) {
                list($product_id, $quantity) = explode(":", $product_detail);
                /**
                 * @var Product $product
                 */
                $product =
                    $this->getDoctrine()->getManager()->getRepository(Product::class)->find($product_id);
                array_push($orders_list, ["oid_".$orders->getId(), $product, $quantity]);
            }
        }

        return $this->render('user/my_orders.html.twig', [
            'orders_list' => $orders_list,
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     * @param User $user
     * @return Response
     */
    public function show(User $user): Response
    {
        $gravatar_hash = md5(strtolower(trim("rootkit@rootkit-lab.org")));
        //$gravatar_hash = md5(strtolower(trim($user->getEmail())));

        if ($user->getId() == $this->getUser()->getId()) {
            return $this->render('user/show.html.twig', [
                'user' => $user,
                'hash' => $gravatar_hash,
            ]);
        } else {
            throw new UnauthorizedHttpException("Nop", "Nop");
        }
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     * @param Request $request
     * @param User $user
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     * @throws Exception
     */
    public function edit(Request $request, User $user,UserPasswordEncoderInterface $passwordEncoder): Response
    {
        if ($user->getId() == $this->getUser()->getId()) {
            $form = $this->createForm(UserType::class, $user);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $plainPass = $form["password"]->getData();
                $password = $passwordEncoder->encodePassword($user, $plainPass);
                $user->setPassword($password);

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($user);
                $entityManager->flush();

                return $this->redirectToRoute('shoptastic');
            }

            return $this->render('user/edit.html.twig', [
                'user' => $user,
                'form' => $form->createView(),
            ]);
        } else {
            throw new UnauthorizedHttpException("Nop", "Nop");
        }

    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     * @param Request $request
     * @param User $user
     * @return Response
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('shoptastic');
    }

}

templates/user/edit.html.twig
{% extends 'shoptastic.html.twig' %}

{% block title %}{{ parent() }} - Edition {{ app.user.username }}{% endblock %}

{% block shoptastic %}
    {% set Allergies = "" %}

    {% for allergie in user.allergies %}
        {% set Allergies = Allergies ~ ", " ~ allergie %}
        {% set Allergies = Allergies|slice(1, Allergies|length )%}
    {% endfor %}

    {% set Diets = "" %}

    {% for diet in user.diet %}
        {% set Diets = Diets ~ ", " ~ diet %}
        {% set Diets = Diets|slice(1, Diets|length )%}
    {% endfor %}

    {% set Fcheck = "" %}
    {% set Mcheck = "" %}

    {% if user.sex %}
        {% set Fcheck = "checked" %}
    {% else %}
        {% set Mcheck = "checked" %}
    {% endif %}
<div class="row">
    <div class="col s10 offset-s1 z-depth-4 card-panel">
            <br>
            {{ form_start(form, { 'action': path('user_edit', {'id': app.user.id})}) }}
                <div class="row">
                    <div class="col s6 offset-s3">
                        <p class="center">Mettre à jour mon profil</p>
                    </div>
                </div>

                {% for label, messages in app.session.flashBag %}
                    {% for message in messages %}
                        <div class="flash-{{ label }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}

                {% if error is defined %}
                    <div class="row">
                        <div class="col s4 offset-s4 red z-depth-4 card-panel">
                            {{ error.messageKey|trans(error.messageData, 'security') }}
                        </div>
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col s5">
                        <label for="firstname">First Name :
                            <input type="text" value="{{ user.firstName }}" />
                        </label>
                    </div>
                    <div class="col s5 offset-s2">
                        <label for="lastName">Last Name :
                            <input type="text" value="{{ user.lastName }}" />
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s5">
                        <label for="birthday">Birthday:
                            <input type="text" value="{{ user.birthday|date('d/m/y') }}" />
                        </label>
                    </div>
                    <div class="col s5 offset-s2">
                        <label for="register">Register At :
                            <input type="text" value="{{ user.registerAt|date('d/m/y') }}" />
                        </label>
                    </div>
                </div>
                <div class="row">
                    <br/>
                    <div class="col s5">
                        <label for="sex">Sex:<br />
                            <input type="radio" class="with-gap" name="sex" {{ Fcheck }}>
                            <span>Female</span>

                            <input type="radio" class="with-gap" name="sex" {{  Mcheck }}>
                            <span>Male</span>
                        </label>
                    </div>
                    <div class="col s5 offset-s2">
                        <label for="address">Address :
                            <input type="text" value="{{ user.address }}" />
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s5">
                        <label for="allergies">Allergies:
                            <input type="text" value="{{ Allergies }}" />
                        </label>
                    </div>
                    <div class="col s5 offset-s2">
                        <label for="diets">Diets :
                            <input type="text" value="{{ Diets }}" />
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s5 ">
                        <label for="allergies">Email:
                            {{ form_widget(form.email) }}
                        </label>
                    </div>
                    <div class="col s5 offset-s2">
                        <label for="diets">Username :
                            {{ form_widget(form.username) }}
                        </label>
                    </div>
                </div>

                {{ form_widget(form.password) }}

                <div class="row">
                    <div class="col s4 offset-s2">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Mettre à jour
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
                </div>

            {{ form_end(form) }}

        <div class="col s4 offset-s2">
            <form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
                <button class="btn">Delete</button>
            </form>
        </div>

        </div>
    </div>
</div>




{% endblock %}

templates/user/my_orders.html.twig
{% extends 'shoptastic.html.twig' %}

{% block title %}

{% endblock %}

{% set order_id_prev = -1 %}
{% set order_id = 0 %}
{% set first_time = true %}

{% block shoptastic %}
    <br />
    <div class="row">
        <div class="col s8 offset-s2">
            <table class="centered striped highlight">
                <thead>
                    <tr>
                        <td align="center">
                            Numéro de commande
                        </td>
                        <td align="center">
                            Produit
                        </td>
                        <td align="center">
                            Quantité
                        </td>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders_list %}
                    <tr>
                        <td>
                        {% if order_id_prev != order[0]|trim('oid_', 'left') %}
                            {% if not first_time %}
                </tbody>
            </table>
        </div>
    </div>
                                <br />
                                <br />
    <div class="row">
        <div class="col s8 offset-s2">
            <table class="centered striped highlight">
                <thead>
                    <tr>
                        <td align="center">
                            Numéro de commande
                        </td>
                        <td align="center">
                            Produit
                        </td>
                        <td align="center">
                            Quantité
                        </td>
                    </tr>
                    </thead>
                        <tr>
                            <td>
                            {% endif %}
                            {{ order[0]|trim('oid_', 'left') }}<br />
                        {% endif %}
                        </td>
                        <td>
                        {{ order[1].name }}<br />
                        </td>
                        <td>
                        {{ order[2] }}<br /><br />
                        </td>
                    </tr>
                        {% set order_id_prev = order[0]|trim('oid_', 'left') %}

                        {% set first_time = false %}
                    {% endfor %}
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}


templates/user/new.html.twig
{% extends 'shoptastic.html.twig' %}

{% block title %}{{ parent() }} - S'enregister chez Foodtastic {% endblock %}

{% block shoptastic %}
    <div class="row">
        <div class="col s6 offset-s3 z-depth-4 card-panel">
            <div class="row">
                <br>
                {{ form_start(form, { 'action': path('app_register')}) }}
                    <div class="row">
                        <div class="col s6 offset-s3">
                            <p class="center">S'incrire</p>
                        </div>
                    </div>

                    {% for label, messages in app.session.flashBag %}
                        {% for message in messages %}
                            <div class="flash-{{ label }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endfor %}

                    {% if error is defined %}
                        <div class="row">
                            <div class="col s4 offset-s4 red z-depth-4 card-panel">
                                {{ error.messageKey|trans(error.messageData, 'security') }}
                            </div>
                        </div>
                    {% endif %}
                    <div class="row">
                        <div class="input-field col s4 offset-s1">
                            {{ form_row(form.username) }}
                        </div>
                        <div class="input-field col s4 offset-s2">
                            {{ form_row(form.email) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s4 offset-s1">
                            {{ form_row(form.password.first) }}
                        </div>
                        <div class="input-field col s4 offset-s2">
                            {{ form_row(form.password.second) }}
                        </div>
                    </div>
                    <div class="col s4 offset-s5">
                        <button class="btn waves-effect waves-light" type="submit" name="action">S'inscrire
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>




{% endblock %}

templates/user/show.html.twig
{% extends 'shoptastic.html.twig' %}

{% block title %}{{ parent() }} - {{ app.user.username }}{% endblock %}

{% block shoptastic %}


    {% set Allergies = "" %}

    {% for allergie in user.allergies %}
        {% set Allergies = Allergies ~ ", " ~ allergie %}
        {% set Allergies = Allergies|slice(1, Allergies|length )%}
    {% endfor %}

    {% set Diets = "" %}

    {% for diet in user.diet %}
        {% set Diets = Diets ~ ", " ~ diet %}
        {% set Diets = Diets|slice(1, Diets|length )%}
    {% endfor %}

    {% set Fcheck = "" %}
    {% set Mcheck = "" %}

    {% if user.sex %}
        {% set Fcheck = "checked" %}
    {% else %}
        {% set Mcheck = "checked" %}
    {% endif %}
    <br />


    <div class="z-depth-4 container" style="height: 350px;">
        <div class="card" style="overflow: visible; height: 100%;">
            <div class="card-image waves-effect waves-block waves-light gravatar-image">
                <img src="https://www.gravatar.com/avatar/{{ hash }}?size=200" class="activator gravatar-image" alt="Gravatar">
            </div>
            <input readonly class="center" type="text" value="{{ user.firstName }} '{{ user.username }}' {{ user.lastName }}" />

            <div class="card-reveal" style="display: none; transform: translateY(0%);">
                <span class="card-title grey-text text-darken-4">Mon Profil<i class="material-icons right">close</i></span>
                <a class='dropdown-trigger right' href='#' data-target='options'><i class="material-icons right">more_vert</i></a>

                <p>
                    <div class="row">
                        <div class="col s5">
                            <label for="firstname">First Name :
                                <input readonly type="text" value="{{ user.firstName }}" />
                            </label>
                        </div>
                        <div class="col s5 offset-s2">
                            <label for="lastName">Last Name :
                                <input readonly type="text" value="{{ user.lastName }}" />
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s5">
                            <label for="birthday">Birthday:
                                <input readonly type="text" value="{{ user.birthday|date('d/m/y') }}" />
                            </label>
                        </div>
                        <div class="col s5 offset-s2">
                            <label for="register">Register At :
                                <input readonly type="text" value="{{ user.registerAt|date('d/m/y') }}" />
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <br/>
                        <div class="col s5">
                            <label for="sex">Sex:<br />
                                <input readonly type="radio" class="with-gap" name="sex" {{ Fcheck }}>
                                <span>Female</span>

                                <input readonly type="radio" class="with-gap" name="sex" {{  Mcheck }}>
                                <span>Male</span>
                            </label>
                        </div>
                        <div class="col s5 offset-s2">
                            <label for="address">Address :
                                <input readonly type="text" value="{{ user.address }}" />
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s5">
                            <label for="allergies">Allergies:
                                <input readonly type="text" value="{{ Allergies }}" />
                            </label>
                        </div>
                        <div class="col s5 offset-s2">
                            <label for="diets">Diets :
                                <input readonly type="text" value="{{ Diets }}" />
                            </label>
                        </div>
                    </div>
                </p>
            </div>
        </div>
    </div>


<ul id='options' class='dropdown-content'>
    <li><a href="{{ path('user_edit', {'id': app.user.id}) }}"><i class="material-icons">edit</i>Editer</a></li>
</ul>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        M.Dropdown.init(document.querySelectorAll('.dropdown-trigger'));
    });
</script>

{% endblock %}